version: '3'
services:
  lamby-web:
    depends_on:
      - postgres
      - minio
    build: .
    ports:
      - '5000:5000'
    environment:
      - MINIO_SERVER_URI=http://minio:9000
      - MINIO_ACCESS_KEY=${ACCESS_KEY}
      - MINIO_SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=postgresql://${ACCESS_KEY}:${SECRET_KEY}@postgres/lamby
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${ACCESS_KEY}
      - POSTGRES_PASSWORD=${SECRET_KEY}
      - POSTGRES_DB=lamby
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=${ACCESS_KEY}
      - MINIO_SECRET_KEY=${SECRET_KEY}
    command: server /data
volumes:
  minio_data:
